export const  VIEW_ALL_MANAGER= " VIEW_ALL_MANAGER";
export const VIEW_ALL_EXECUTIVE = "VIEW_ALL_EXECUTIVE";
export const VIEW_ALL_EXECUTIVE_BY_ID = "VIEW_ALL_EXECUTIVE_BY_ID";
export const VIEW_ALL_MANAGER_BY_ID = "VIEW_ALL_MANAGER_BY_ID";
export const SET_MANAGER_NAME = "SET_MANAGER_NAME";
export const SET_MANAGER_EMAIL_ID = "SET_MANAGER_EMAIL_ID";
export const SET_MANAGER_CONTACT_NUMBER = "SET_MANAGER_CONTACT_NUMBER";
export const SET_MANAGER_EMP_SHORT_ID = "SET_MANAGER_EMP_SHORT_ID";
export const SET_CATAGORY_ID = "SET_CATAGORY_ID";
export const SET_MANAGER_ID = "SET_MANAGER_ID";
export const SET_EXECUTIVE_NAME = "SET_EXECUTIVE_NAME";
export const SET_EXECUTIVE_ID = "SET_EXECUTIVE_ID";
export const SET_EXECUTIVE_EMAIL_ID = "SET_EXECUTIVE_EMAIL_ID";
export const SET_EXECUTIVE_CONTACT_NUMBER = "SET_EXECUTIVE_CONTACT_NUMBER";
export const SET_EXECUTIVE_EMP_SHORT_ID = "SET_EXECUTIVE_EMP_SHORT_ID";
export const SEARCH_EMPLOYEE= "SEARCH_EMPLOYEE";
export const SEARCH_FILTERED_EXECUTIVE= "SEARCH_FILTERED_EXECUTIVE";
export const SEARCH_FILTERED_LEADS= "SEARCH_FILTERED_LEADS";
export const SET_MANAGER_CATAGORY_ID= "SET_MANAGER_CATAGORY_ID";


