export const SET_CLIENTS = "SET_CLIENTS";
export const SET_CLIENTS_FOLLOWUP = "SET_CLIENTS_FOLLOWUP";
export const SET_CLIENT_ID = "SET_CLIENT_ID";
export const SET_ALL_CLIENT_DETAILS = "SET_ALL_CLIENT_DETAILS";
export const SET_FILTERED_ALL_CLIENT_DETAILS = "SET_FILTERED_ALL_CLIENT_DETAILS";
export const SET_CLIENT_NAME = "SET_CLIENT_NAME";
export const SET_NEW_CLIENT = "SET_NEW_CLIENT";
export const SET_CONF_CLIENT="SET_CONF_CLIENT";
export const SET_RTO_REG="SET_RTO_REG";
export const SET_NUM_PLATE="SET_NUM_PLATE";
 